.PHONY: clean All

All:
	@echo "----------Building project:[ PAC1 - Debug ]----------"
	@cd "PAC1" && "$(MAKE)" -f  "PAC1.mk"
clean:
	@echo "----------Cleaning project:[ PAC1 - Debug ]----------"
	@cd "PAC1" && "$(MAKE)" -f  "PAC1.mk" clean
